{
  "created_at": "2021-01-24T05:25:47.043Z",
  "title": "Pip has dropped support for Python 2",
  "url": "https://pip.pypa.io/en/stable/news/#id1",
  "author": "groodt",
  "points": 232,
  "num_comments": 161,
  "_tags": [
    "story",
    "author_groodt",
    "story_25888249",
    "front_page"
  ],
  "objectID": "25888249",
  "original_created_at": "2021-01-24T02:01:43.000Z",
  "localize": [
    {
      "locale": "zh",
      "title": "Pip已经放弃了对Python 2的支持"
    },
    {
      "locale": "zh-Hant",
      "title": "Pip已經放棄了對Python 2的支持"
    }
  ],
  "image": ""
}